// Remove index.html that is generated by Gulp
// Remove folder for assets

var config = require('../gulp.config.js')();
var gulp = require('gulp');
var del = require('del');

gulp.task('clean', function () {
    return del(config.assets);
});

gulp.task('removeLayout', function () {
    return del(config.index);
});